version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3.9-rc-management
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - rabbitmq-storage:/var/lib/rabbitmq/
      - rabbitmq-storage:/var/log/rabbitmq
    networks:
      - rabbitmq_net
networks:
  rabbitmq_net:
    driver: bridge
volumes:
  rabbitmq-storage:
