version: '3.8'

services:
  prometheus:
    image: prom/prometheus
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    environment:
      GF_INSTALL_PLUGINS: 'grafana-clock-panel,grafana-simple-json-datasource'
    restart: always
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
      #   托管数据
      - grafana-storage:/var/lib/grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
volumes:
  gragana-storage:
